repository: pseudoforceyt/projectTitin
url: "https://pseudoforceyt.github.io"
baseurl: "/projectTitin"
siteIcon: /media/android-chrome-192x192.png
siteYear: 2024
siteFooterlink: /about
showinSearchEngines: true
# googleAnalyticsID: 

siteNav:
   - name: About
     url: about
     newtab: true
   - name: 'Useful Resources'
     url: useful
   - name: 'YouTube'
     url: socials

theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
