repository: pseudoforceyt/projectTitin
url: "https://pseudoforceyt.github.io"
baseurl: "/projectTitin"
siteIcon: /media/android-chrome-192x192.png
siteYear: 2023
siteFooterlink: /about
showinSearchEngines: true
# googleAnalyticsID: 

siteNav:
   - name: About
     url: about
     newtab: true
   - name: 'Notes Catalog'
     url: catalog
   - name: 'Other Socials'
     url: socials

theme: minima
# plugins:
#   - jekyll-feed
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
